### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by 0adri3n** [PrincTwilig/GPT4Moodle#9]
Hi,

Everything's fine for the download and installation but when i click on the button to load answer, generating is infinite.

I'm on Chromium installed via snapd on Ubuntu.

Screen : 

![image](https://user-images.githubusercontent.com/62818208/222119229-3a644097-7eae-426b-a58e-f0a00eadd20a.png)

**Comment by PrincTwilig** [comment]
Hi,

Thank you for your request, usually such an error occurs in users who use vpn. If that's not the problem, can you look at the network tab in the extension developer tools to see if there are any requests there.

dev tools (service worker) here:
![image](https://user-images.githubusercontent.com/93429979/222122928-3fc9685f-d21a-4236-9960-068ab7cebe26.png)

networ tab (open it before pressing the button):
![image](https://user-images.githubusercontent.com/93429979/222123018-2ca33347-7226-4c8d-9751-e7e6807dc15c.png)

tip:
for test you can use already passed test

**Comment by 0adri3n** [comment]
Ty for the answer

![image](https://user-images.githubusercontent.com/62818208/222123742-c37e70ac-bb0a-411b-9cef-eb4c0f61fab0.png)

There is no requests.

A friend told me that i need to add number to questions cuz the answer number class dont exist on Moodle

**Comment by PrincTwilig** [comment]
check for the errors in console on the page with buttons, after pressing button, on my moodle all the answers has class "d-flex w-100" if your not there will be an error

**Comment by 0adri3n** [comment]
I'll test

My friend send me an adjustement : 

```
getQuestion() {
      let dict = {};
      // on change le foreach
      this.element.querySelectorAll('.d-flex.w-100').forEach((ans, answernumber) => {
          // On enleve cette ligne let answernumber = ans.getElementsByClassName('answernumber')[0].innerHTML[0];
          let text = ans.getElementsByClassName('flex-fill')[0].innerHTML;
          dict[answernumber] = text;
      });
  
      const prompt = {
          'question': this.element.getElementsByClassName('qtext')[0].innerHTML,
          'answers': dict
      };
  
      let request = "Нижче буде наведене питання і варіанти відповіді, вибери одну правильну відповідь, та запиши відповідь в форматі json з двома ключами letter(буква відповіді) та explanation(пояснення чому ця відповідь), напиши відповідь лише у json нічого іншого\n\n";
  
      request += `${prompt.question}\n`;
  
      for (let key in prompt.answers) {
          request += `${key}. ${prompt.answers[key]}\n`;
      }
  
      return request;
  }
```

Then a new error : 

![image](https://user-images.githubusercontent.com/62818208/222128623-886d82fa-1575-4fd8-9733-0fa04f09f61e.png)

I guess i just need to log in chatGPT on the same browser

**Comment by PrincTwilig** [comment]
about login into chatGPT your right, but with solution of your friend there is an issue, we need that row to know what question refers to what letter, so we need to find other way (way that your moodle gives), can you send screenshot how answers in your moodle written?

like this:
![image](https://user-images.githubusercontent.com/93429979/222130160-2e69fa79-1ffb-4f10-b4b1-89e763deb9b1.png)

**Comment by 0adri3n** [comment]
Mine is :

![image](https://user-images.githubusercontent.com/62818208/222163212-869870ed-199c-4ff8-a165-b1effeb2bc2b.png)

**Comment by PrincTwilig** [comment]
and what inside of any "r" classes? i need to see what nodes keeps text and letter

**Comment by 0adri3n** [comment]
![image](https://user-images.githubusercontent.com/62818208/222194565-6a4e9a01-d9ac-44d1-9a59-df9c6f933c40.png)

**Comment by PrincTwilig** [comment]
ok, i think i fixed that part with answernumber, its already in main branch, if you want you can download source and test. It take some time to update in chrome web(chrome aways check every updates of apps). By the way i dont think extension will answer quiz that you showing, its work better with text, but why not to try :). Also thank you for that request.

**Comment by 0adri3n** [comment]
Apparently it works !!

![image](https://user-images.githubusercontent.com/62818208/222354696-97a9ebd9-55ec-4ff8-b184-5c47ce6d4905.png)

gj to u sir, this a good one !
